version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: inventory_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: inventory_app
    depends_on:
      - mongo
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017}
      - MONGO_DB_NAME=${MONGO_DB_NAME:-inventory_db}

volumes:
  mongo_data:
